# Backend Dockerfile
FROM node:22

# Set working dir
WORKDIR /app

# Copy package.json & lock first
COPY package*.json ./

# Install deps
RUN npm install

# Copy source
COPY . .

# Expose backend port
EXPOSE ${PORT}

# Start server
CMD ["npm", "start"]
